application: hyperpronto
version: 2
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /favicon.ico
  static_files: static/logo.png
  upload: static/logo.png
  
- url: /.*
  script: _go_app
