application: hyperpronto
version: 2
runtime: go
api_version: go1

default_expiration: "1d"

handlers:
- url: /css
  static_dir: static/css
  http_headers:
    Vary: Accept-Encoding

- url: /js
  static_dir: static/js
  http_headers:
    Vary: Accept-Encoding

- url: /font
  static_dir: static/font
  http_headers:
    Vary: Accept-Encoding

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: _go_app

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (tumblr\.html)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (static/img/.*)|
 (static/psd/.*)|
 )$